import type { Lesson } from "@/content/types";
import { QUIZ_DAY_1 } from "@/content/quizzes";

/** День 1 — Знакомство с Metro (~15 минут). */
export const DAY_1_LESSONS: Lesson[] = [
  {
    id: "l-d1-welcome",
    slug: "dobro-pozhalovat",
    title: "Добро пожаловать",
    shortDescription: "Знакомство с приложением и командой Metro.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 1,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Добро пожаловать в команду MetroFitness! Это твой первый день адаптации." },
      { id: "b2", type: "INFO_CARD", title: "Метрик рядом", body: "Наш напарник Метрик проведёт тебя через все три дня." },
    ],
  },
  {
    id: "l-d1-how-learning-works",
    slug: "kak-ustroeno-obuchenie",
    title: "Как устроено обучение",
    shortDescription: "Дни, уроки, тесты и XP.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 2,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Обучение разбито на дни. Каждый день — несколько коротких уроков и тест." },
      { id: "b2", type: "CHECKLIST", title: "Как проходить", items: ["Открывай уроки по порядку", "Проходи тест дня", "Получай XP и растёшь в рейтинге"] },
    ],
  },
  {
    id: "l-d1-history",
    slug: "istoriya-metrofitness",
    title: "История MetroFitness",
    shortDescription: "Как появилась сеть клубов Metro.",
    durationMinutes: 3,
    xpReward: 50,
    isRequired: true,
    accessLevel: "onboarding",
    order: 3,
    status: "PUBLISHED",
    videoUrl: "placeholder://history",
    blocks: [
      { id: "b1", type: "VIDEO", url: "placeholder://history", caption: "Короткое видео об истории сети." },
      { id: "b2", type: "TEXT", text: "MetroFitness выросла из одного клуба в сеть по всей стране." },
    ],
  },
  {
    id: "l-d1-mission",
    slug: "missiya-kompanii",
    title: "Миссия компании",
    shortDescription: "Зачем мы работаем и к чему стремимся.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 4,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Наша миссия — помогать людям становиться сильнее и здоровее." },
      { id: "b2", type: "SUMMARY", points: ["Забота о клиенте", "Результат", "Команда"] },
    ],
  },
  {
    id: "l-d1-difference",
    slug: "chto-otlichaet-metrofitness",
    title: "Что отличает MetroFitness",
    shortDescription: "Наши принципы и сервис.",
    durationMinutes: 3,
    xpReward: 50,
    isRequired: true,
    accessLevel: "onboarding",
    order: 5,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "INFO_CARD", title: "Сервис уровня Metro", body: "Внимание к каждому гостю на каждом шаге." },
      { id: "b2", type: "TEXT", text: "Мы отличаемся сервисом, стандартами и заботой о результате клиента." },
    ],
  },
  {
    id: "l-d1-test",
    slug: "test-dnya-1",
    title: "Тест дня",
    shortDescription: "Короткая проверка знаний первого дня.",
    durationMinutes: 3,
    xpReward: 60,
    isRequired: true,
    accessLevel: "onboarding",
    order: 6,
    status: "PUBLISHED",
    quiz: QUIZ_DAY_1,
    blocks: [
      { id: "b1", type: "TEXT", text: "Проверим, что запомнилось за первый день." },
      { id: "b2", type: "QUIZ", quizId: QUIZ_DAY_1.id },
    ],
  },
];
