import type { Lesson } from "@/content/types";
import { QUIZ_DAY_3, QUIZ_FINAL_ATTESTATION } from "@/content/quizzes";

/** День 3 — Стандарты работы (~15 минут + аттестация). */
export const DAY_3_LESSONS: Lesson[] = [
  {
    id: "l-d3-standards",
    slug: "korporativnye-standarty",
    title: "Корпоративные стандарты",
    shortDescription: "Правила, которые объединяют команду.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 1,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Корпоративные стандарты — единые правила работы во всех клубах сети." },
    ],
  },
  {
    id: "l-d3-appearance",
    slug: "vneshniy-vid",
    title: "Внешний вид",
    shortDescription: "Дресс-код и опрятность.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 2,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "CHECKLIST", title: "Стандарт внешнего вида", items: ["Форма Metro", "Опрятность", "Бейдж"] },
    ],
  },
  {
    id: "l-d3-communication",
    slug: "obshchenie-s-klientami",
    title: "Общение с клиентами",
    shortDescription: "Вежливость, забота, помощь.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 3,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "INFO_CARD", title: "Главный принцип", body: "Вежливость и искренняя забота о госте." },
    ],
  },
  {
    id: "l-d3-safety",
    slug: "bezopasnost",
    title: "Безопасность",
    shortDescription: "Безопасность гостей и сотрудников.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 4,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Безопасность — приоритет. Знай правила и действия в нештатных ситуациях." },
    ],
  },
  {
    id: "l-d3-craft",
    slug: "rabota-s-craft",
    title: "Работа с Craft",
    shortDescription: "Рабочая система сотрудника.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 5,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Craft — рабочая система, где ведётся ежедневная работа сотрудника." },
    ],
  },
  {
    id: "l-d3-contracts-cash",
    slug: "dogovory-kassa-otchetnost",
    title: "Договоры, касса и отчётность",
    shortDescription: "Базовые правила оформления и отчётности.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 6,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "CHECKLIST", title: "Важно", items: ["Точность оформления", "Соблюдение регламента", "Аккуратная отчётность"] },
    ],
  },
  {
    id: "l-d3-test",
    slug: "test-dnya-3",
    title: "Тест дня",
    shortDescription: "Проверка знаний о стандартах.",
    durationMinutes: 2,
    xpReward: 60,
    isRequired: true,
    accessLevel: "onboarding",
    order: 7,
    status: "PUBLISHED",
    quiz: QUIZ_DAY_3,
    blocks: [
      { id: "b1", type: "QUIZ", quizId: QUIZ_DAY_3.id },
    ],
  },
  {
    id: "l-d3-final-attestation",
    slug: "itogovaya-attestatsiya",
    title: "Итоговая аттестация",
    shortDescription: "Финальная проверка перед подтверждением управляющим.",
    durationMinutes: 3,
    xpReward: 100,
    isRequired: true,
    accessLevel: "onboarding",
    order: 8,
    status: "PUBLISHED",
    quiz: QUIZ_FINAL_ATTESTATION,
    blocks: [
      { id: "b1", type: "TEXT", text: "Итоговая аттестация подводит итог трёх дней адаптации." },
      { id: "b2", type: "QUIZ", quizId: QUIZ_FINAL_ATTESTATION.id },
    ],
  },
];
