import type { Lesson } from "@/content/types";
import { QUIZ_DAY_2 } from "@/content/quizzes";

/** День 2 — Знание продукта (~15 минут). */
export const DAY_2_LESSONS: Lesson[] = [
  {
    id: "l-d2-club-card",
    slug: "chto-vhodit-v-klubnuyu-kartu",
    title: "Что входит в клубную карту",
    shortDescription: "Состав и преимущества карты Metro.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 1,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Клубная карта — это доступ к зонам клуба, групповым программам и сервисам." },
      { id: "b2", type: "CHECKLIST", title: "В карту входит", items: ["Тренажёрные зоны", "Групповые программы", "Раздевалки и душевые"] },
    ],
  },
  {
    id: "l-d2-training-types",
    slug: "vidy-trenirovok",
    title: "Виды тренировок",
    shortDescription: "Кардио, силовые, функциональные.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 2,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "В клубе доступны кардио, силовые и функциональные тренировки." },
      { id: "b2", type: "SUMMARY", points: ["Кардио", "Силовые", "Функциональные"] },
    ],
  },
  {
    id: "l-d2-zones",
    slug: "zony-kluba",
    title: "Зоны клуба",
    shortDescription: "Как устроено пространство клуба.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 3,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "INFO_CARD", title: "Зоны", body: "Кардио, свободные веса, тренажёры и групповые программы." },
    ],
  },
  {
    id: "l-d2-equipment",
    slug: "trenazhery-i-oborudovanie",
    title: "Тренажёры и оборудование",
    shortDescription: "Ключевое оборудование и его назначение.",
    durationMinutes: 3,
    xpReward: 50,
    isRequired: true,
    accessLevel: "onboarding",
    order: 4,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Познакомься с базовым оборудованием клуба." },
      { id: "b2", type: "EQUIPMENT_CARD", equipmentId: "eq-treadmill" },
      { id: "b3", type: "EQUIPMENT_CARD", equipmentId: "eq-rack" },
      { id: "b4", type: "EQUIPMENT_CARD", equipmentId: "eq-cable" },
    ],
  },
  {
    id: "l-d2-group-programs",
    slug: "gruppovye-programmy",
    title: "Групповые программы",
    shortDescription: "Форматы групповых тренировок Metro.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 5,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "GROUP_CLASS_CARD", groupClassId: "gc-cycle" },
      { id: "b2", type: "GROUP_CLASS_CARD", groupClassId: "gc-hiit" },
      { id: "b3", type: "GROUP_CLASS_CARD", groupClassId: "gc-yoga" },
    ],
  },
  {
    id: "l-d2-personal-training",
    slug: "personalnye-trenirovki",
    title: "Персональные тренировки",
    shortDescription: "Работа с персональным тренером.",
    durationMinutes: 2,
    xpReward: 40,
    isRequired: true,
    accessLevel: "onboarding",
    order: 6,
    status: "PUBLISHED",
    blocks: [
      { id: "b1", type: "TEXT", text: "Персональные тренировки помогают клиенту достигать целей быстрее." },
    ],
  },
  {
    id: "l-d2-test",
    slug: "test-dnya-2",
    title: "Тест дня",
    shortDescription: "Проверка знаний о продукте.",
    durationMinutes: 2,
    xpReward: 60,
    isRequired: true,
    accessLevel: "onboarding",
    order: 7,
    status: "PUBLISHED",
    quiz: QUIZ_DAY_2,
    blocks: [
      { id: "b1", type: "QUIZ", quizId: QUIZ_DAY_2.id },
    ],
  },
];
